language: node_js
dist: trusty
addons:
  chrome: stable
notifications:
  email: false
cache:
  directories:
    - node_modules
sudo: required
node_js:
  - "10.15.3"
env:
  global:
    - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false
# allow headful tests
before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - npm i
script:
  - npm run testCI